const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {chromium} = require('playwright');
const root = path.resolve(__dirname,'..');
const baseline = require('./baseline-destinations.json');
const base = process.env.PORTAL_PREVIEW || 'http://127.0.0.1:8777';
const output = process.env.SCREENSHOT_DIR;
if (!output) throw new Error('Set SCREENSHOT_DIR outside the public checkout');
const keys = baseline.keys;
const protectedKeys = ['home','dns','docker','files','drop','shlink','tools','pdf','lab','convert','news','paste','beszel','router','sunshine','actions'];
const fixture = {checked_at:new Date().toISOString(),services:keys.filter(key=>key!=='news').map(key=>({key,status:protectedKeys.includes(key)?'protected':'online'}))};
let response = fixture;
const errors=[];
async function overflow(page) {
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'horizontal overflow');
  const clipped = await page.locator('.service-card h3,.feature-copy,.hero-copy').evaluateAll(elements=>elements.filter(el=>el.scrollWidth>el.clientWidth+1).length);
  assert.equal(clipped,0,'clipped text');
}
(async()=>{
  fs.mkdirSync(output,{recursive:true});
  const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE});
  try {
    const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'dark'});
    await context.route('https://status-api.amsyarputra.net/**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(response)}));
    const page=await context.newPage();
    page.on('pageerror',error=>errors.push(error.message));
    await page.goto(base,{waitUntil:'networkidle'});
    assert.equal(await page.locator('[data-service]').count(),21);
    for (const href of baseline.hrefs) assert(await page.locator('a').evaluateAll((anchors,href)=>anchors.some(a=>a.getAttribute('href')===href),href),'missing destination '+href);
    for (const key of keys) assert(await page.locator('[data-status-key="'+key+'"]').count(),'missing key '+key);
    for (const key of protectedKeys) assert.match(await page.locator('[data-service="'+key+'"] .access-label').innerText(),/Protected/);
    assert.equal(await page.locator('[data-service="lab"] .status-pill').innerText(),'Protected');
    assert.equal(await page.locator('[data-service="news"] .status-pill').innerText(),'Unknown');
    await page.locator('[data-category-filter="creative"]').click();
    assert.equal(await page.locator('[data-service]:visible').count(),3);
    await page.locator('[data-category-filter="all"]').click();
    await page.locator('#service-search').fill('document');
    assert(await page.locator('[data-service="docs"]').isVisible());
    await page.locator('#service-search').fill('no-such-destination');
    assert(await page.locator('#search-empty').isVisible());
    await page.locator('#clear-search').click();
    assert.equal(await page.locator('[data-service]:visible').count(),21);
    await page.keyboard.press('Meta+k');
    assert(await page.locator('#command-palette').isVisible());
    await page.locator('#command-search').fill('mini photo');
    assert.equal(await page.locator('#command-results a').count(),1);
    await page.keyboard.press('ArrowDown');
    assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('href')),'https://photo.amsyarputra.net');
    await page.keyboard.press('Escape');
    assert(!(await page.locator('#command-palette').isVisible()));
    await page.locator('[data-theme-toggle]').click();
    assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
    response={services:[]};
    await page.reload({waitUntil:'networkidle'});
    assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
    assert.equal(await page.locator('[data-service="docs"] .status-pill').innerText(),'Unknown');
    await overflow(page);
    await page.screenshot({path:path.join(output,'desktop-light.png'),fullPage:true});
    await page.locator('[data-theme-toggle]').click();
    assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
    await page.screenshot({path:path.join(output,'desktop-dark.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await overflow(page);
    await page.locator('[data-menu-toggle]').click();
    assert(await page.locator('#site-nav').isVisible());
    await page.locator('#site-nav a').first().click();
    assert(!(await page.locator('#site-nav').isVisible()));
    await page.evaluate(()=>scrollTo(0,0));
    await page.screenshot({path:path.join(output,'mobile-dark.png'),fullPage:true});
    await page.setViewportSize({width:320,height:740});await overflow(page);
    await page.setViewportSize({width:768,height:1024});await overflow(page);
    await page.emulateMedia({reducedMotion:'reduce'});
    assert.equal(await page.locator('.service-card').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');
    response=fixture;
    await page.setViewportSize({width:1440,height:1000});
    await page.goto(base+'/status.html',{waitUntil:'networkidle'});
    assert.equal(await page.locator('[data-status-key]').count(),22);
    assert.equal(await page.locator('#services-unknown').innerText(),'1');
    assert.equal(await page.locator('#overall-status').innerText(),'Unknown');
    response={services:keys.map(key=>({key,status:protectedKeys.includes(key)?'protected':'online'}))};
    await page.locator('#refresh-status').click();
    await page.waitForFunction(()=>document.getElementById('overall-status').textContent==='Protected checks present');
    response={services:[]};
    await page.locator('#refresh-status').click();
    await page.waitForFunction(()=>document.getElementById('status-error').hidden===false);
    assert.equal(await page.locator('#services-unknown').innerText(),'22');
    await overflow(page);
    await page.screenshot({path:path.join(output,'status-dark.png'),fullPage:true});
    for (const route of ['privacy.html','vpn.html','404.html']) {
      await page.goto(base+'/'+route,{waitUntil:'networkidle'});await overflow(page);
      await page.setViewportSize({width:390,height:844});await overflow(page);
      await page.setViewportSize({width:1440,height:1000});
    }
    await page.goto(base+'/vpn.html#moonlight-sunshine');
    assert(await page.locator('#moonlight-sunshine').isVisible());
    assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'),'noindex, nofollow');
    const noJS=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844},colorScheme:'light'});
    const fallback=await noJS.newPage();
    await fallback.goto(base,{waitUntil:'networkidle'});
    assert.equal(await fallback.locator('[data-service]:visible').count(),21);
    assert(await fallback.locator('#site-nav').isVisible());
    assert.equal(await fallback.locator('[data-theme-toggle]:visible').count(),0);
    await overflow(fallback);
    await fallback.goto(base+'/status.html');
    assert.equal(await fallback.locator('[data-status-key]').count(),22);
    await noJS.close();
    assert.deepEqual(errors,[],'browser errors');
    await context.close();
    console.log('PASS: preserved destinations/keys/access labels, category/search/empty state, keyboard palette, theme persistence, API Protected/Unknown semantics, reduced motion, 320/390/768/1440px layouts, secondary pages, no-JS navigation');
    console.log('Screenshots use unavailable-status fixtures, not claimed live health.');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
